In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("spam.csv")
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [3]:
df.Category.value_counts()

ham     4825
spam     747
Name: Category, dtype: int64

In [4]:
df['spam'] = df['Category'].apply(lambda x: 1 if x =='spam' else 0)

In [5]:
df.shape

(5572, 3)

In [6]:
df.head()

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [7]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df.Message, df.spam, test_size=0.2)

In [8]:
type(X_train)

pandas.core.series.Series

In [9]:
X_train[:4]

3807    URGENT! We are trying to contact you. Last wee...
1981                               Sorry, I'll call later
4746    Camera - You are awarded a SiPix Digital Camer...
4099       I think just yourself …Thanks and see you tomo
Name: Message, dtype: object

In [10]:
y_train[:4]

3807    1
1981    0
4746    1
4099    0
Name: spam, dtype: int64

In [11]:
X_train.values

array(['URGENT! We are trying to contact you. Last weekends draw shows that you have won a £900 prize GUARANTEED. Call 09061701851. Claim code K61. Valid 12hours only',
       "Sorry, I'll call later",
       'Camera - You are awarded a SiPix Digital Camera! call 09061221066 fromm landline. Delivery within 28 days.',
       ...,
       'Wen ur lovable bcums angry wid u, dnt take it seriously.. Coz being angry is d most childish n true way of showing deep affection, care n luv!.. kettoda manda... Have nice day da.',
       "Sorry, I'll call later",
       "As per your request 'Maangalyam (Alaipayuthe)' has been set as your callertune for all Callers. Press *9 to copy your friends Callertune"],
      dtype=object)

In [12]:
type(X_train.values)

numpy.ndarray

In [13]:
## Create bag of words representation using CountVectorizer

In [14]:
from sklearn.feature_extraction.text import CountVectorizer

v = CountVectorizer()

X_train_cv = v.fit_transform(X_train.values)
X_train_cv

<4457x7717 sparse matrix of type '<class 'numpy.int64'>'
	with 59369 stored elements in Compressed Sparse Row format>

In [15]:
X_train_cv.toarray()[:2][0]

array([0, 0, 0, ..., 0, 0, 0])

In [16]:
X_train_cv.shape

(4457, 7717)

In [17]:
v.get_feature_names_out()[1060]

'arabian'

In [18]:
v.vocabulary_

{'urgent': 7189,
 'we': 7396,
 'are': 1064,
 'trying': 7044,
 'to': 6921,
 'contact': 2010,
 'you': 7678,
 'last': 4043,
 'weekends': 7417,
 'draw': 2459,
 'shows': 6137,
 'that': 6795,
 'have': 3377,
 'won': 7547,
 '900': 734,
 'prize': 5430,
 'guaranteed': 3283,
 'call': 1617,
 '09061701851': 202,
 'claim': 1844,
 'code': 1906,
 'k61': 3906,
 'valid': 7226,
 '12hours': 302,
 'only': 4954,
 'sorry': 6329,
 'll': 4176,
 'later': 4049,
 'camera': 1637,
 'awarded': 1180,
 'sipix': 6181,
 'digital': 2338,
 '09061221066': 199,
 'fromm': 3038,
 'landline': 4026,
 'delivery': 2258,
 'within': 7521,
 '28': 387,
 'days': 2209,
 'think': 6830,
 'just': 3899,
 'yourself': 7689,
 'thanks': 6789,
 'and': 972,
 'see': 5984,
 'tomo': 6944,
 'don': 2421,
 'floppy': 2922,
 'snappy': 6273,
 'happy': 3354,
 'gay': 3106,
 'chat': 1760,
 'service': 6031,
 'with': 7518,
 'photo': 5196,
 'upload': 7177,
 '08718730666': 151,
 '10p': 280,
 'min': 4498,
 'stop': 6485,
 'our': 5013,
 'texts': 6783,
 '0871246032

In [19]:
X_train_np = X_train_cv.toarray()
X_train_np[0]

array([0, 0, 0, ..., 0, 0, 0])

In [20]:
np.where(X_train_np[0]!=0)

(array([ 202,  302,  734, 1064, 1617, 1844, 1906, 2010, 2459, 3283, 3377,
        3906, 4043, 4954, 5430, 6137, 6795, 6921, 7044, 7189, 7226, 7396,
        7417, 7547, 7678]),)

In [22]:
X_train[:4]

3807    URGENT! We are trying to contact you. Last wee...
1981                               Sorry, I'll call later
4746    Camera - You are awarded a SiPix Digital Camer...
4099       I think just yourself …Thanks and see you tomo
Name: Message, dtype: object

In [23]:
X_train_np[0][1064]

1

In [24]:
# Train Naive Bayes Model

from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()
model.fit(X_train_cv, y_train)

MultinomialNB()

In [25]:
X_test

1466    YOU 07801543489 are guaranteed the latests Nok...
5384    How are you babes. Hope your doing ok. I had a...
4434    Can u look 4 me in da lib i got stuff havent f...
3411    Joy's father is John. Then John is the ____ of...
2231    Hey... Thk we juz go accordin to wat we discus...
                              ...                        
2718                                       Okie.. Thanx..
4743                Ya very nice. . .be ready on thursday
4579    Urgent! call 09066350750 from your landline. Y...
252     Wen ur lovable bcums angry wid u, dnt take it ...
1127    Not tonight mate. Catching up on some sleep. T...
Name: Message, Length: 1115, dtype: object

In [26]:
X_test_cv = v.transform(X_test)

In [27]:
from sklearn.metrics import classification_report

y_pred = model.predict(X_test_cv)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00       987
           1       0.98      0.97      0.97       128

    accuracy                           0.99      1115
   macro avg       0.99      0.98      0.98      1115
weighted avg       0.99      0.99      0.99      1115



In [28]:
emails = [
    'Hey mohan, can we get together to watch footbal game tomorrow?',
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!'
]

emails_count = v.transform(emails)
model.predict(emails_count)

array([0, 1])

In [30]:
# Train the model using sklearn pipeline and reduce number of lines of code

In [31]:
from sklearn.pipeline import Pipeline

clf = Pipeline([
    ('vectorizer', CountVectorizer()),
    ('nb', MultinomialNB())
])

In [32]:
clf.fit(X_train, y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [33]:
y_pred = clf.predict(X_test)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00       987
           1       0.98      0.97      0.97       128

    accuracy                           0.99      1115
   macro avg       0.99      0.98      0.98      1115
weighted avg       0.99      0.99      0.99      1115

